### ISSUE TITLE
Missing tags after 3.5

### ISSUE THREAD

**Issue by eugene-dounar** [brunoric/docker-hhvm#5]
I can only pull tags listed here: https://hub.docker.com/r/brunoric/hhvm/tags/

    $ docker run --rm -ti brunoric/hhvm:3.10 bash
    Unable to find image 'brunoric/hhvm:3.10' locally
    Pulling repository docker.io/brunoric/hhvm
    Tag 3.10 not found in repository docker.io/brunoric/hhvm

**Comment by brunoric** [comment]
@eugene-dounar this bug is not related directly with the Docker images nor HHVM builds. The problem is the Docker Hub. In fact I found a couple of issues regarding gcc compilation. When a lot of RAM is required, Docker Hub builds have problems and do not build properly. I am working in a new workflow to auto build these images (using travis-ci). As soon everything is ok I will inform here. I am also updating the documentation to make it more consistently across the hubs (Github and Docker Hub).

Thank you for your feedback!

**Comment by brunoric** [comment]
Hi @eugene-dounar, after some days working on the automated build flow for the repository (and the images) I figure out the problem. The problem was that Docker Hub, Travis-CI and CircleCI can't build HHVM (since version 3.7) due RAM memory limitations in its VM's, so I built the images locally with success in Linux and Mac hosts (trough docker-toolbox and docker-machine VMs) and pushed it to Docker Hub. To properly build HHVM was required something like ~3GB of RAM. I will continue the journey to automated the builds but for now, as I said, none of the most popular free CIs can build it. 

Thank you again for the feedback.
